### ISSUE TITLE
[FEAT] Entity 설계

### ISSUE THREAD

**Issue by yeseul106** [Team-Puzzling/Puzzling_Server#5]
## 🚀 About Issue 🚀

- Entity 설계를 합니다.

## ✅ Todo 

- [ ] 프로젝트 Entity 구현
- [ ] 회고 Entity 구현
- [ ] 회고 템플릿 Entity 구현
